version: "3.7"
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    depends_on: ["avnius"]

  avnius:
    build: .
    ports:
      - 5000:5000
    restart: always
